[default]
#FastAPI
fastapi_title = "type-registry-service"
fastapi_description = "This service supports .."


resources_path = "@format {env[BASE_DIR]}/resources/linkset"
log_file = "@format {env[BASE_DIR]}/logs/dsg.log"
#log_file = "/Users/akmi/git/ekoi/poc-4-wim/type-verification-service/logs/dsg.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"